# Generated by Django 3.0.3 on 2020-05-07 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_auto_20200507_2147'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
