# Generated by Django 3.0.3 on 2020-03-10 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20200302_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='short_descripion',
            new_name='short_description',
        ),
    ]
